#!/bin/sh

BASEDIR=$(pwd)
BUILDTYPE=${BUILDTYPE:-Release}

cd out/${BUILDTYPE}/obj.target

if [ "$(uname)" = "SunOS" ]; then
  /usr/xpg4/bin/find . -path "**/*v8*/**/*.o" | xargs ar cqs libv8_monolith.a
  /usr/xpg4/bin/find . -path "**/*icu*/**/*.o" | xargs ar cqs libv8_monolith.a
elif [ "$(uname)" = "Linux" ]; then
  for lib in `find . -path './deps/v8/gypfiles/*.a'`;
    do ar -t $lib | xargs ar -q libv8_monolith.a;
  done;
  for lib in `find . -path './tools/icu/*.a'`;
    do ar -t $lib | xargs ar -q libv8_monolith.a;
  done;
else
  echo "Unsupported Platform"
  exit
fi

mv libv8_monolith.a $BASEDIR/out/${BUILDTYPE}
